# Generated by Django 3.1.2 on 2020-10-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدرها'},
        ),
    ]
