# Generated by Django 3.1.2 on 2020-10-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس های کاربران'},
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='title',
        ),
        migrations.AddField(
            model_name='contactus',
            name='text',
            field=models.TextField(default=2, verbose_name='متن پیام'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='عنوان پیام'),
        ),
    ]
