# Generated by Django 3.1.2 on 2020-10-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0002_auto_20201029_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده/نشده'),
        ),
    ]
